### PR TITLE
Add more improvements about I18n and l10n

### PR DESCRIPTION
**Pull request by macagua**
Add more improvements about the I18n and l10n

- Added Transifex.net service integration to manage the translation process.
- Updated Spanish translation
- Updated README file
- Updated the i18n support

### CODE REVIEW

**Comment by pbauer** [comment]
Looks good to me

**Comment by pbauer** [comment]
@macagua could you fix the last flake8-errors in the test as well?

**Comment by macagua** [comment]
@pbauer done!

**Comment by macagua** [comment]
Hi @pbauer and @vangheem 

Can you review this pull request, if all ok can merge it?

Thank you

**Comment by macagua** [comment]
@pbauer thanks :+1:

**Pull request merged**
